# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  displayName: 'Install Terraform latest'

- script: 'ssh-keygen -q -t rsa -N '''' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1'
  displayName: 'Command Line Script'
  
 

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'Container-Registry-Service-Connection'
    repository: frontend
    command: build
    Dockerfile: frontend/Dockerfile
- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'Container-Registry-Service-Connection'
    command: push
- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'Container-Registry-Service-Connection'
    repository: api
    command: build
    Dockerfile: api/Dockerfile
- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'Container-Registry-Service-Connection'
    command: push
    
  
